services:
  mysql:
    image: mysql:8.0
    container_name: gudpipol-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gudpipol_db_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - gudpipol_mysql_dev_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  gudpipol_mysql_dev_data:
